class Columns:
    AGE = "age"
    JOB = "job"
    MARITAL = "marital"
    EDUCATION = "education"
    DEFAULT = "default"
    BALANCE = "balance"
    HOUSING = "housing"
    LOAN = "loan"
    CONTACT = "contact"
    MONTH = "month"
    DAY = "day"
    DURATION = "duration"
    CAMPAIGN = "campaign"
    PDAYS = "pdays"
    PREVIOUS = "previous"
    POUTCOME = "poutcome"
    OUTPUT = "y"
